# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GrowthBook-IOS' do
  platform :ios, '12.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GrowthBook-IOS
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Logging'
end

target 'GrowthBook-TV' do
  platform :tvos, '12.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GrowthBook-TV
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Logging'
end

target 'GrowthBook-Watch' do
  platform :watchos, '5.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GrowthBook-TV
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Logging'
end

target 'GrowthBookTests' do
  platform :ios, '12.0'
  use_frameworks!
  # Pods for testing
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Logging'
end

