name: Deploy

on:
  workflow_run:
    workflows: ["CI main"]
    types:
      - completed

jobs:
  release:
    runs-on: macos-14
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - uses: actions/checkout@v3
      with:
        clean: 'true'
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Prepare for release
      run:  |
        set -eo pipefail
        export LIB_VERSION=${{ steps.gitversion.outputs.SemVer }}
        pod spec lint --allow-warnings

